<?php

namespace AppBundle\Repository;

/**
 * BeerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeerTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
