<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * LikingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRatedBeers(User $user)
    {
        return $this->createQueryBuilder('l')
            ->where('l.author = :userId')
            ->setParameter('userId', $user->getId())
            ->getQuery()
            ->getResult();
    }
}
