<?php

namespace AppBundle\Repository;

/**
 * LikingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikingRepository extends \Doctrine\ORM\EntityRepository
{
}
